import type { Metadata } from "next";
import { Dancing_Script, Lora } from 'next/font/google'; 
import "./globals.scss";
import React from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const dancingScript = Dancing_Script({
  weight: '400', 
  subsets: ['latin'],
  style: ['normal'],
  display: 'swap'
});

const lora = Lora({
  weight: '400', 
  subsets: ['latin'],
  style: ['normal', 'italic'],
  display: 'swap'
});


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dancingScript.className} ${lora.className}`}>
        {children}
      </body>
    </html>
  );
}